### ISSUE TITLE
Link to the paper is 404'ing

### ISSUE THREAD

**Issue by sander-bol** [gglucass/AQUSA#6]
The bit.ly link at the top of the README.MD redirects to https://www.dropbox.com/s/e6gv2yee5u8vizc/Forging%20High-Quality%20User%20Stories%20-%20Towards%20a%20Discipline%20for%20Agile%20Requirements.pdf?dl=0 , which is a 404.

**Comment by gglucass** [comment]
Thanks for notifying me. Updated to a new link, which coincidentally is also a new paper.

FYI: the instructions for installing AQUSA are outdated and it's unlikely you'll get it to work easily. We're going to work on improving that soon-ish. Hopefully.
Furthermore, the front-end is here: https://github.com/gglucass/grimm
